name = "xyrtania"
compatibility_date = "2026-06-23"
pages_build_output_dir = "./dist"

[main]
main = "src/backend/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "xyrtania-db"
database_id = "67857f77-3294-486d-bc3a-569913a9822a"
